### ISSUE TITLE
Apache S2Graph

### ISSUE THREAD

**Issue by pluradj** [rayokota/hgraphdb#1]
Hello! I'm excited to hear about your development work on an Apache TinkerPop graph database based on Apache HBase. I read through your [blog post](https://rayokota.wordpress.com/2016/11/10/hgraphdb-hbase-as-a-tinkerpop-graph-database/) too.

Have you tried reaching out to the [Apache S2Graph community](https://s2graph.incubator.apache.org/community.html) to contribute to their effort? For example, they have already begun work on the TinkerPop implementation, see [S2GRAPH-72](https://issues.apache.org/jira/browse/S2GRAPH-72) and [S2Graph-80](https://issues.apache.org/jira/browse/S2GRAPH-80). I didn't see a JIRA ticket opened for vertex indices, but you could certainly open up and contribute to that feature as well.

**Comment by rayokota** [comment]
Thank you, yes, I'm aware that S2Graph is looking at implementing TinkerPop.  Another criterion that I didn't mention is that I'm looking for a pure Java solution, whereas S2Graph is written in Scala.  My company Yammer has moved away from Scala.

https://codahale.com/the-rest-of-the-story/

**Comment by pluradj** [comment]
Thanks, makes sense. I know many others prefer pure Java over Scala. Definitely reach out to the [Apache TinkerPop dev list](https://lists.apache.org/list.html?dev@tinkerpop.apache.org) if you need help. Thanks!
