### ISSUE TITLE
How to increase the performance of inserting edges in different proecesses?

### ISSUE THREAD

**Issue by youzp** [rayokota/hgraphdb#10]
In general,vertex and edge data are separated in different files,so they are inserted in different processes.
Firstly it need to query source and destination vertex,and then add the edge.
The time to query a vertex may take more than 100 ms,this will greatly affect the efficiency of insertion.
If the amount of edge data is particularly large, the insertion time will be particularly long.
How to improve the performance of inserting edges in this case?
```
HBaseBulkLoader loader = new HBaseBulkLoader(graph);
Vertex src = graph.vertex((long)1);
Vertex dst = graph.vertex((long)2);
loader.addEdge(src, dst, "edge", "P3", "V3"); 
```

**Comment by rayokota** [comment]
Try this

```
HBaseBulkLoader loader = new HBaseBulkLoader(graph);
Vertex src =new HBaseVertex(graph, (long)1);
Vertex dat =new HBaseVertex(graph, (long)2);
loader.addEdge(src, dst, "edge", "P3", "V3"); 
```

**Comment by youzp** [comment]
hi, @rayokota Thank you for your proposal,it's perfect.
Now about 500 edges per second can be inserted into the HBase.
Regardless of data consistency problems, are there other ways to improve the efficiency of bulk insert?

**Comment by rayokota** [comment]
Ok, I've adding the ability to skip writing to the WAL in the bulk loader.  Please use 0.4.5

`config.setBulkLoaderSkipWAL(true);`
