### ISSUE TITLE
why getStartKey(regionCount) is Integer.MAX_VALUE / regionCount

### ISSUE THREAD

**Issue by msjbear** [rayokota/hgraphdb#12]
hi @rayokota, I have a doubt that why `getStartKey(regionCount)` is `Integer.MAX_VALUE / regionCount`, but not 0
```
admin.createTable(tableDescriptor, getStartKey(regionCount), getEndKey(regionCount), regionCount);

private static byte[] getStartKey(int regionCount) {
        return Bytes.toBytes((Integer.MAX_VALUE / regionCount));
    }
private static byte[] getEndKey(int regionCount) {
        return Bytes.toBytes((Integer.MAX_VALUE / regionCount * (regionCount - 1)));
    }
```

**Comment by rayokota** [comment]
According to the JavaDoc for createTable, "The start key specified will become the end key of the first region of the table"

[](https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/client/Admin.html#createTable-org.apache.hadoop.hbase.HTableDescriptor-byte:A-byte:A-int-)
