### ISSUE TITLE
How to set vertex or edge TTL?

### ISSUE THREAD

**Issue by youzp** [rayokota/hgraphdb#14]
In my department, HBase table permissions are controlled, can not be easily added or deleted.In this case, if I want to periodically clear the edge data or vertex data, I can not use ‘truncate table’, only set TTL for each data. So i modify the code and add a line of code in function "public Iterator<Put> constructInsertions()":
```
io.hgraphdb.mutators.EdgeIndexWriter
io.hgraphdb.mutators.EdgeWriter

put.setTTL(3600*24*7);
```
Is there any other better way?

**Comment by rayokota** [comment]
The only other way would be to explicitly delete the data, but that would not be very efficient, especially for large graphs.
