### ISSUE TITLE
Batch delete in HBaseBulkLoader

### ISSUE THREAD

**Issue by youzp** [rayokota/hgraphdb#18]
My little suggestion—Most business services are incremental updates, so the batch delete command is very useful in HBaseBulkLoader.
How to delete vertex and vertex index using HBaseBulkLoader?

**Comment by rayokota** [comment]
The issue is that when vertices or edges are deleted, it requires a cascaded delete of other rows (which must be retrieved by Scans), so is not really suitable for a bulk loader.  For now please use

`vertex.remove()`
