### ISSUE TITLE
Table auto creation and deletion for label_metadata and label_connections tables

### ISSUE THREAD

**Issue by cristiancalugaru** [rayokota/hgraphdb#2]
In HBaseGraphUtils, createTables and dropTables are missing tables label_metadata and label_connections. In case one uses useSchema=true, and tries to add schema enforcements with graph.createLabel calls, it will fail since the 2 tables do not get created.

HBaseGraphUtils line 112 should contain:
createTable(config, admin, Constants.LABEL_METADATA, HConstants.FOREVER);
createTable(config, admin, Constants.LABEL_CONNECTIONS, HConstants.FOREVER);

and line 154:
dropTable(config, admin, Constants.LABEL_METADATA);
dropTable(config, admin, Constants.LABEL_CONNECTIONS);

**Comment by rayokota** [comment]
Good catch, thanks
