### ISSUE TITLE
Will a gremlin traversal make use of created Indexes?

### ISSUE THREAD

**Issue by tellisnz** [rayokota/hgraphdb#21]
Hi Robert,

For an index created like:

`graph.createIndex(ElementType.VERTEX, "test", "key");`

Will a gremlin traversal such as:

`graph.traversal().V().has("test", "key", "value");`

use this index? Or is it only used when doing something like:

`graph.verticesByLabel("test", "key", "value");`

**Comment by rayokota** [comment]
Yes, the traversal will use the index.
