### ISSUE TITLE
Supported HBase and Hadoop versions?

### ISSUE THREAD

**Issue by ThijsBroersen** [rayokota/hgraphdb#22]

**Comment by ThijsBroersen** [comment]
I am using HBase 1.2.4 and Hadoop 2.7.2 but keep getting the following error when opening the database connection: ```io.hgraphdb.HBaseGraphException: org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator```

**Comment by rayokota** [comment]
This is an HBase issue.  It appears you are using a newer version of Guava (perhaps pulled in from Hadoop), whereas HBase relies on an older version.

See https://issues.apache.org/jira/browse/HBASE-14126

Also see https://issues.apache.org/jira/browse/HBASE-14963

There are 2 things you can try:

1) Use the old version of Guava required by HBase
2) Use the new version of Guava, but copy the old version of Stopwatch.java into your project.

If you need further help, please try the HBase user mailing list.
