### ISSUE TITLE
mapreduce index populate

### ISSUE THREAD

**Issue by LarryLp** [rayokota/hgraphdb#26]
run a MapReduce job using the hbase command:
hbase io.hgraphdb.mapreduce.index.PopulateIndex \
    -t vertex -l person -p name -op /tmp -ca gremlin.hbase.namespace=testgraph
Error:java.io.IOException:Type mismatch in value from map:expected org.apache.hadoop.hbase.KeyValue,received org.apache.hadoop.hbase.client.Result

**Comment by rayokota** [comment]
Please try with Hadoop 2.7.1 or later

**Comment by LarryLp** [comment]
I was using Hadoop2.7.3,Hbase1.1.2,spark 1.6.3 of HDP2.6.  Can you help me with this issue?thx!

**Comment by rayokota** [comment]
Ok, I was able to reproduce, a fix is coming.

**Comment by rayokota** [comment]
Ok, fixed in 1.0.1

**Comment by LarryLp** [comment]
Got it! It works! thanks for your project
