### ISSUE TITLE
Using the Gremlin Console to analyse data in hgraphdb，input:  g.V("006281338731").out() ; has no result

### ISSUE THREAD

**Issue by emyfan** [rayokota/hgraphdb#28]
I have inserted my graph data (spark dataframe format) into HBase, by following [this documenation](https://hbase.apache.org/book.html#_sparksql_dataframes)

Then I use HGraphDB in the Gremlin console, and run the following:
`graph=HBaseGraph.open("test3","10.9.11.1", "/hbase")`
`g=graph.traversal()`
`g.E()`

the I can get the edges：
`==>e[006281338731:15980203][006281338731-contacts->15980203]`
`==>e[00821065463:15754630][00821065463-contacts->15754630]`
`==>e[00827048583:18941000][00827048583-contacts->18941000]`
`................`

when I input:
`g.V("006281338731")`
get the vertex:
`==>v[006281338731]`

**but when I input：
`g.V("006281338731").out()`
there is no result**

**obviously, there exists en edge `[006281338731-contacts->15980203]`
so I don't understand why the input `g.V("006281338731").out()`  doesn't get the edge.**

**Can you help me with the problem? Is there anything wrong when I inserted data into Hbase?**

here is the process of inserting data:

**1. Define catalog**

 def vertexCatalog =
        s"""{
      "table":{"namespace":"testGraph", "name":"vertices","tableCoder":"org.apache.spark.sql.execution.datasources.hbase.types.HGraphDB", "version":"2.0"},
      "rowkey":"key",
      "columns":{
      "id":{"cf":"rowkey", "col":"key", "type":"string"},
      "label":{"cf":"f", "col":"~l", "type":"string"},
      "name":{"cf":"f", "col":"name", "type":"string"}}}""".stripMargin

def edgeCatalog =
        s"""{
      "table":{"namespace":"testGraph", "name":"edges","tableCoder":"org.apache.spark.sql.execution.datasources.hbase.types.HGraphDB", "version":"2.0"},
      "rowkey":"key",
      "columns":{
          "id":{"cf":"rowkey", "col":"key", "type":"string"},
          "relationship":{"cf":"f", "col":"~l", "type":"string"},
          "src":{"cf":"f", "col":"~f", "type":"string"},
          "dst":{"cf":"f", "col":"~t", "type":"string"},
          "create_time":{"cf":"f", "col":"create_time", "type":"string"}}}""".stripMargin   
     

**2. generate the DataFrame**
      case class Vertex(id: String, name: String, label: String)
      case class Edge(id: String, src: String, create_time: String, dst: String, relationship: String)
     
    val DataDF=sc.textFile("hdfs:///node.txt").map(_.split(",")).map(p => Vertex(p(0),p(1),p(2))).toDF()

**3.  inserted the dataframe into hbase**
`DataDF.write.options(Map(HBaseTableCatalog.tableCatalog -> vertexCatalog, HBaseTableCatalog.newTable -> "5")).format("org.apache.spark.sql.execution.datasources.hbase").save()`

**Comment by rayokota** [comment]
Hi, importing graph data through the Spark-HBase connector (SHC) and reading it through HGraphDB/TinkerPop is not currently supported.   Only importing graph data through HGraphDB/TinkerPop and then reading through SHC is supported.

When graph data is imported through SHC, it does not populate the edgeIndices table; it only populates the edges and vertices tables.

Is it possible for you to use the HBaseBulkLoader to populate your data?  Otherwise I would need to provide you with a Map-Reduce utility to populate the edgeIndices table after importing data through SHC.

**Comment by emyfan** [comment]
###  Hi rayokota, thanks for help
### I have populate my data by using HBaseBulkLoader you recommended, but I still can't visit my data through Gremlin Console.
Here is the code of loading data:
1. Preparing data via a MapReduce job:
`hadoop jar /usr/hdp/2.5.3.0-37/hbase/lib/hbase-server-1.1.2.2.5.3.0-37.jar importtsv -Dhbase.zookeeper.quorum=172.16.**.** -Dzookeeper.znode.parent=/hbase-unsecure -Dimporttsv.bulk.output=hdfs:///graph_data/result -Dimporttsv.separator=',' -Dimporttsv.columns=HBASE_ROW_KEY,f:~l,f:name bulkloader:vertices hdfs:///graph_data/test_node.txt 
`

2.Completing the data load:

`./bin/hbase org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles hdfs:///graph_data/result bulkloader:vertices `

###  when the loading is completed, I can see the data in the HBase 

![44](https://user-images.githubusercontent.com/31723710/30310292-4d6eaa24-97c2-11e7-9a70-fc69bb1f2088.jpg)


### but when I visit the data using  Gremlin Console.
`graph=HBaseGraph.open("bulkloader","172.16.*.*", "/hbase-unsecure")`
`g=graph.traversal()`
`g.V()`

### Here comes the error:
![33](https://user-images.githubusercontent.com/31723710/30310305-650533b0-97c2-11e7-9768-327f9453a8d9.jpg)

### Could you help me with this problem？I don't know how to solve this.

### Besides, I have seen you also support Giraph and Flink Gelly for Graph Analytics , can  we use Giraph and Flink Gelly to import data ? 
### Thank you very much!
