### ISSUE TITLE
populate my data by using HBaseBulkLoader you recommended, but I still can't visit my data through Gremlin Console.

### ISSUE THREAD

**Issue by emyfan** [rayokota/hgraphdb#29]
### I have populate my data by using HBaseBulkLoader you recommended, but I still can't visit my data through Gremlin Console.
Here is the code of loading data:
1. Preparing data via a MapReduce job:
`hadoop jar /usr/hdp/2.5.3.0-37/hbase/lib/hbase-server-1.1.2.2.5.3.0-37.jar importtsv -Dhbase.zookeeper.quorum=172.16.**.** -Dzookeeper.znode.parent=/hbase-unsecure -Dimporttsv.bulk.output=hdfs:///graph_data/result -Dimporttsv.separator=',' -Dimporttsv.columns=HBASE_ROW_KEY,f:~l,f:name bulkloader:vertices hdfs:///graph_data/test_node.txt 
`

2.Completing the data load:

`./bin/hbase org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles hdfs:///graph_data/result bulkloader:vertices `

###  when the loading is completed, I can see the data in the HBase 

![44](https://user-images.githubusercontent.com/31723710/30310292-4d6eaa24-97c2-11e7-9a70-fc69bb1f2088.jpg)

### but when I visit the data using  Gremlin Console.
`graph=HBaseGraph.open("bulkloader","172.16.*.*", "/hbase-unsecure")`
`g=graph.traversal()`
`g.V()`

### Here comes the error:
![33](https://user-images.githubusercontent.com/31723710/30310305-650533b0-97c2-11e7-9768-327f9453a8d9.jpg)

**Comment by rayokota** [comment]
Sorry for the confusion, I meant for you to use this HBaseBulkLoader:

https://github.com/rayokota/hgraphdb#bulk-loading

https://static.javadoc.io/io.hgraphdb/hgraphdb/1.0.1/io/hgraphdb/HBaseBulkLoader.html

Data cannot be imported through the other frameworks, only through HBaseBulkLoader or the TinkerPop API.

**Comment by rayokota** [comment]
Here is an example use:

https://github.com/rayokota/hgraphdb/blob/master/src/test/java/io/hgraphdb/HBaseBulkLoaderTest.java

**Comment by bantao** [comment]
@emyfan, through hgraphdb, data in hbase is serialized(see ValueUtils.java), so you should write code(java) to finish bulkload.
