### ISSUE TITLE
Question on graph traversal

### ISSUE THREAD

**Issue by cristiancalugaru** [rayokota/hgraphdb#3]
Hi,
First of all thanks for writing this tool, I am in the process of evaluating it for a project which involves some basic graph processing.
I have a question about one call - HBaseGraph#allVertices(Object fromId, int limit) - I am trying to use this to start from an existing Vertex, and get all other Vertices connected to it. Is this the intended usage of this call, or I should be doing this in a different way? Basically I'm looking for a Depth-First or Breadth-First traversal of the graph, and thought this would be a simpler way of doing it. if not, could you recommend how this can be done the easiest?

**Comment by rayokota** [comment]
Hi,
That call is for simply paging through all vertices in the graph.  The order that the vertices is returned is indeterminate.  If you are interested in depth-first or breadth-first traversals, a good first place to look is

https://github.com/tinkerpop/gremlin/wiki/Depth-First-vs.-Breadth-First

In general, if you have other questions about TinkerPop, I would recommend posting them to the user group, which will be able to give you more definitive answers:

https://groups.google.com/forum/#!forum/gremlin-users

**Comment by ovidiupetridean** [comment]
Hi,

I'm having some issues with graph traversal as well. Basically what I'm trying to do is:

`  GraphTraversal<Vertex, Vertex> inspiredFrom = hBaseGraph.traversal().V(source1Vertex).outE("inspiredFrom").inV().inE("inspiredFrom").outV().value();
        GraphTraversal result = inspiredFrom.valueMap("distance");
        result.next();`

And I get this error:
`java.lang.ClassCastException: io.hgraphdb.HBaseVertex cannot be cast to org.apache.tinkerpop.gremlin.structure.Property

	at org.apache.tinkerpop.gremlin.process.traversal.step.map.PropertyValueStep.map(PropertyValueStep.java:40)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:37)
`
Is there another way I could cycle through the results?

Thanks!
