### ISSUE TITLE
why io.hgraphdb.groovy.plugin.HBaseGremlinPlugin is drop in 1.0.x?

### ISSUE THREAD

**Issue by bantao** [rayokota/hgraphdb#30]
when i test  hgraph in gremlin console, this step: <code>:plugin use io.hgraphdb</code> isn't work, and i found io.hgraphdb.groovy.plugin.HBaseGremlinPlugin is drop in 1.0.x, why?

**Comment by rayokota** [comment]
You need to use TinkerPop 3.3.0.  It has been renamed to io.hgraphdb.jsr223.HBaseGraphGremlinPlugin.

**Comment by bantao** [comment]
oh, thx very much!
