### ISSUE TITLE
Setting Table name

### ISSUE THREAD

**Issue by ronaldFeri** [rayokota/hgraphdb#33]
Hi, 

How can I set table name, while writing or reading, in Hgraphdb configuration? I couldn't be able to find any relevant property. 

-thanks 
Ronald

**Comment by rayokota** [comment]
You can't set the table name but you can set the namespace and/or a prefix for the table.

Configuration cfg = new HBaseGraphConfiguration().setGraphNamespace("mygraph").setGraphTablePrefix("myprefix")
