### ISSUE TITLE
Read vertices

### ISSUE THREAD

**Issue by ronaldFeri** [rayokota/hgraphdb#35]
Hi, 
I followed your example and added two vertices and an edge via following piece of code: 
```
        HBaseGraphConfiguration cfg = new HBaseGraphConfiguration()
                .setInstanceType(InstanceType.DISTRIBUTED)
                .setGraphNamespace("fg2")
                .setCreateTables(false)
                .setGraphTablePrefix("myprefix")
                .setRegionCount(3);
        HBaseGraph graph = (HBaseGraph) GraphFactory.open(cfg);
        Vertex v1 = graph.addVertex(T.id, 1, T.label, "person", "name", "John");
        Vertex v2 = graph.addVertex(T.id, 2, T.label, "person", "name", "Sally");
```
 
but when trying to read a vertex with following command: 

      graph.vertex(1).property("person") 

Hgraphdb said that there is no such a vertex: 
 ```
   Exception in thread "main" io.hgraphdb.HBaseGraphNotFoundException: Vertex does not exist: 1
	at io.hgraphdb.readers.VertexReader.load(VertexReader.java:32)
	at io.hgraphdb.readers.VertexReader.load(VertexReader.java:15)
	at io.hgraphdb.models.ElementModel.load(ElementModel.java:48)
	at io.hgraphdb.HBaseElement.load(HBaseElement.java:126)
	at io.hgraphdb.HBaseGraph.vertex(HBaseGraph.java:267)
	at testHgraphDb.main(testHgraphDb.java:24)
```        
I checked tables via shell and tables are created and the mentioned vertices and edge are added. I was wondering if you could tell what I should do? 
-Thanks 
Ronald

**Comment by rayokota** [comment]
Sorry, I've changed the example to use longs instead of ints as IDs.  Due to some quirks with TinkerPop interoperability, int IDs get converted to longs.  It's best to use either longs or Strings as IDs.

```
        Vertex v1 = graph.addVertex(T.id, 1L, T.label, "person", "name", "John");
        Vertex v2 = graph.addVertex(T.id, 2L, T.label, "person", "name", "Sally");
```

Then the following works (your example above is querying on a label not a property):

      System.out.println(graph.vertex(1L).property("name").value());

**Comment by rayokota** [comment]
Ok, I've also made a slight change so that int IDs are converted to longs during queries, so your original example should work :)
