### ISSUE TITLE
The speed of HBaseBulkLoader.addVertex() become slow as vertices increases

### ISSUE THREAD

**Issue by wolfbloodzzx** [rayokota/hgraphdb#37]
I try to import a graph containing ten million vertices into the database. To improve performance, I used the HBaseBulkLoader.addVertex () to add vertices. At first, the speed will be very fast, but as the number of vertices increases, the speed become too slow. 
I am a novice in using hbase and hgarphdb. I am confused why it becomes slow, and what can I do to optimize it?

**Comment by bantao** [comment]
in my way, maybe you can try this(suppose your data is in Hive):
1.write MR program to generate HFiles.
2.use "LoadIncrementalHFiles" to upload HFiles to HBase.
in this way, you should konw the data's schema/format in HBase, so you can write the correct MR program to generate the correct HFiles. by the way, the code file 'ValueUtils.java' maybe useful for you!

**Comment by rayokota** [comment]
Yes, you can do as @bantao said.  You may also want to set your region count so that splits don't keep happening.

```
new HBaseGraphConfiguration().setRegionCount(...) 
```

**Comment by wolfbloodzzx** [comment]
Thanks a lot. I try to upload HFiles to HBase directly, and It works.
