### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by ronaldFeri** [rayokota/hgraphdb#38]
Is there any way to set connection pool size?

**Comment by rayokota** [comment]
You can set arbitrary HBase configuration parameters using `new HBaseGraphConfiguration().set("...", "...")`.  For specific parameters, you can try `hbase.client.ipc.pool.size`, see https://www.slideshare.net/xefyr/hbasecon2014-low-latency for other parameters.

This is more of an HBase question, so you can also try the HBase user mailing list for more guidance on configuring and tuning HBase.
