### ISSUE TITLE
Graph Traversal

### ISSUE THREAD

**Issue by ovidiupetridean** [rayokota/hgraphdb#4]
Hi,

I'm having some issues with graph traversal as well. Basically what I'm trying to do is:

`  GraphTraversal<Vertex, Vertex> inspiredFrom = hBaseGraph.traversal().V(source1Vertex).outE("inspiredFrom").inV().inE("inspiredFrom").outV().value();
        GraphTraversal result = inspiredFrom.valueMap("distance");
        result.next();`

And I get this error:
`java.lang.ClassCastException: io.hgraphdb.HBaseVertex cannot be cast to org.apache.tinkerpop.gremlin.structure.Property

	at org.apache.tinkerpop.gremlin.process.traversal.step.map.PropertyValueStep.map(PropertyValueStep.java:40)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:37)
`
Is there another way I could cycle through the results?

Thanks!

**Comment by rayokota** [comment]
Try removing the ".value()".  That is for obtaining the value of a property.  

If you want more definitive answers, please try the TinkerPop user list:

https://groups.google.com/forum/#!forum/gremlin-users
