### ISSUE TITLE
Read HGraphDB edges based on their labels

### ISSUE THREAD

**Issue by f-hashemi** [rayokota/hgraphdb#40]
Hi,
I'm trying to create Gelly graph from HGraphDB. I followed your [example](https://github.com/rayokota/hgraphdb#graph-analytics-with-flink-gelly) and everything is ok!
But, I want to get edges based on their **labels** instead of their property.

For example, I need just read edges which have label "port" with all their properties.  Is there any idea?

**Comment by rayokota** [comment]
Hi, try specifying the property as `~l` for the label.

**Comment by f-hashemi** [comment]
"~l" just gives all edges with their labels, while I want to get edges (and their properties) with the specific label. For example, the graph has two type of vertices: user and movie. Each of these nodes has its properties:

- user: name, age, address
- movie: genre, director, time
I want to get "user" nodes and all of their properties (name, age, address).

**Comment by rayokota** [comment]
Flink Gelly only lets you associate a single value with a vertex or an edge.  So If you want multiple properties to be represented by this single value, then you will need to use a Java-serializable object or a Kryo-serializable object as the property value.

**Comment by f-hashemi** [comment]
Can I get the nodes of one specific label (not all labels) from HGraphDB?

**Comment by rayokota** [comment]
No, but you can create an index to get all vertices with a particular label and property value.

**Comment by f-hashemi** [comment]
Can you help me more with your solution, please?

**Comment by rayokota** [comment]
If you want to get all the vertices with a specific label, you can also add the label as a property, say `plabel`, then create an index

```
graph.createIndex(ElementType.VERTEX, "port", "plabel");
```

Then you can do

```
Iterator<Vertex> it = graph.verticesByLabel("port", "plabel", "port");
```

**Comment by f-hashemi** [comment]
What about getting all edges which have the specific label?

**Comment by rayokota** [comment]
There is not a straightforward way to do that.  You can get all edges using `allEdges()` and filter them.
