### ISSUE TITLE
Handle Exception if an edge does not have a property

### ISSUE THREAD

**Issue by f-hashemi** [rayokota/hgraphdb#44]
Hi,
When I get edges based on one property in flink, **all edges** should have this property and any of edges do not have that property an Exception will be thrown.
Is it possible that we can handle this exception and just return edges which have this property and ignore other edges?
I used this commands:
```java
env.createInput(new HBaseEdgeInputFormat<>(hconf, property), typeHint)
```

**Comment by rayokota** [comment]
This is fixed, please try 1.0.9

**Comment by rayokota** [comment]
From the stack trace, it looks like the HBase thread pools have been closed prematurely:

```
Caused by: java.util.concurrent.RejectedExecutionException: Task org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture@58dd520a rejected from java.util.concurrent.ThreadPoolExecutor@471cea3a[**Terminated**, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 36]
```

Are you calling `HBaseGraphUtils.closeConnections()` or doing something else that might teardown the HBase thread pools before Flink has finished?

**Comment by f-hashemi** [comment]
No, I do not call anything to cause this problem.
I use exactly the same code for HGraphDB 1.0.6 and 1.0.9. In version 1.0.6 everything is ok about  HBase thread pools and I just get "The property does not exist as it has no key, value, or associated element" exception.

**Comment by rayokota** [comment]
Ok, please try 1.10.  I removed the call to `HBaseGraphUtils.closeConnections` in `HBaseGraph.close`, since that is the only change between 1.0.6 and 1.0.9 that could be causing this.  If you need to clean up connections, you can call `HBaseGraphUtils.closeConnections` explicitly.

**Comment by f-hashemi** [comment]
That works correctly.
Thanks.
