### ISSUE TITLE
[Question] Spark DataFrame Bulkload to HgraphDB

### ISSUE THREAD

**Issue by prithvi514** [rayokota/hgraphdb#48]
This is more of a question than an issue.

Is there any example that we can refer to bulk load data from spark dataframe/rdd to Hgraphdb? 

Please redirect me to appropriate usergroup or Gitter if they exist.

**Comment by rayokota** [comment]
Currently going from Spark to HGraphDB is not supported, only going from HGraphDB to Spark.
