### ISSUE TITLE
how to query vertex if I do not know what label is

### ISSUE THREAD

**Issue by youzp** [rayokota/hgraphdb#51]
### Version: 2.0+ 
I have added vertex index on field "comm_id", in order to avoid the emergence of hot spots I use a lot of labels in the vertex index table, how to query "comm_id"  if I do not know what label is.

```
// add index
graph.createIndex(ElementType.VERTEX, "1label", "comm_id");
graph.createIndex(ElementType.VERTEX, "2label", "comm_id");
......
graph.createIndex(ElementType.VERTEX, "xlabel", "comm_id");

// add vertex
loader.addVertex(T.id, 1000L, T.label, "1label", "comm_id", 100)
loader.addVertex(T.id, 1000L, T.label, "2label", "comm_id", 200)
......
loader.addVertex(T.id, 1000L, T.label, "xlabel", "comm_id", 300)
```

**Comment by rayokota** [comment]
Have you considered setting the ID to the value of label + comm_id, especially if that is the primary way you access vertices?

**Comment by youzp** [comment]
@rayokota  thanks!
