### ISSUE TITLE
why edgeindex has CREATED_AT

### ISSUE THREAD

**Issue by teenyboy** [rayokota/hgraphdb#54]
Hi,
   why we need the CREATED_AT, What is its role?
   Thanks for your enthusiastic reply！

[PS: I deal the hot spot when I create vertexIndices by HexStringSplit Style,It is a violent method ]

VertexIndexModel:

public byte[] serializeForRead(String label, boolean isUnique, String key, Object value) {
        PositionedByteRange buffer = new DynamicPositionedMutableByteRange(4096);
        buffer.put((byte) '0');
        byte[] prefix = serializePrefix(label, isUnique, key);
        ValueUtils.serializeWithSalt(buffer, prefix);
        if (value != null) {
            ValueUtils.serialize(buffer, value);
        }
        buffer.setLength(buffer.getPosition());
        buffer.setPosition(0);
        byte[] bytes = new byte[buffer.getRemaining()];
        buffer.get(bytes);
        byte[] firstByte = getMd5FirstByte(bytes);
        bytes[0] = firstByte[0];
        bytes[1] = firstByte[1];
        return bytes;
    }

public byte[] serializeForWrite(Vertex vertex, boolean isUnique, String key) {
        PositionedByteRange buffer = new DynamicPositionedMutableByteRange(4096);
        buffer.put((byte) '0');//fill to 00~FF
        byte[] prefix = serializePrefix(vertex.label(), isUnique, key);
        ValueUtils.serializeWithSalt(buffer, prefix);
        ValueUtils.serialize(buffer, vertex.value(key));

        //get the front bytes
        PositionedByteRange bufferPrefix = buffer.deepCopy();
        bufferPrefix.setLength(bufferPrefix.getPosition());
        bufferPrefix.setPosition(0);
        byte[] bytesPrefix = new byte[bufferPrefix.getRemaining()];
        bufferPrefix.get(bytesPrefix);

        if (!isUnique) {
            ValueUtils.serialize(buffer, vertex.id());
        }
        buffer.setLength(buffer.getPosition());
        buffer.setPosition(0);
        byte[] bytes = new byte[buffer.getRemaining()];
        buffer.get(bytes);

        //replace the front two byte to hex string byte
        byte[] firstByte = getMd5FirstByte(bytesPrefix);
        bytes[0] = firstByte[0];
        bytes[1] = firstByte[1];
        return bytes;
    }
 
   /**
     * get the first two bytes based on md5 of prefix+value
     * @param bytes
     * @return
     */
    private static byte[] getMd5FirstByte(byte[] bytes){

        byte[] byteContent = new byte[2];
        byteContent[0] = '0';
        byteContent[1] = '0';
        try {
            String rowkey = new String(bytes,"gbk");
            String rowkeyMd5 = getMD5(rowkey);
            if(StringUtils.isNotEmpty(rowkeyMd5)){
                byte[] rowkeyMd5Bytes = rowkeyMd5.getBytes("gbk");
                if(rowkeyMd5Bytes.length > 0){
                    byteContent[0] = rowkeyMd5Bytes[0];
                    byteContent[1] = rowkeyMd5Bytes[1];
                }
            }
            return byteContent;
        }catch (Exception e){
            byteContent[0] = 'f';
            byteContent[1] = 'f';
            return byteContent;
        }
    }

    /**
     * get md5 by the prefix+value
     * @param str 
     * @return 
     */
    public static String getMD5(String str) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(str.getBytes("gbk"));
            return new BigInteger(1, md.digest()).toString(16);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

when I have 20 fragmentations, it is average.
if I will use the api in the future to insert and search datas.  Is there a problem with this method?

**Comment by rayokota** [comment]
`CREATED_AT` is used as a "dummy" index to ensure efficient retrieval of ALL adjacent vertices of a given vertex.

(I quickly looked at your code, it should be fine as long as you don't require range queries/pagination)
