### ISSUE TITLE
How to parallelize hbase ops? 

### ISSUE THREAD

**Issue by coxycoxwell** [rayokota/hgraphdb#55]
First of all, thanks for this great work!
We were using Janusgraph to create and query our graph database. 
A short time ago, we came up with your project as a solution to our needs, because we only use hbase as storage. We have updated some of your code in order to meet our user requirements which were all went so good.
But now, we are struggling about the traversal speed of the application. While we query a vertex neighbor edges and vertices, firstly we scan hbase (edge indices) with the vertex id provided (which we need to parallelize those scan ops). After getting edge and vertex IDs as a result to those scans, we have to get corresponding edge/vertex objects with some "get"s from hbase (which we also need to parallelize). Janusgraph had a parameter "storage.backend.parallel-ops" which parallelize backend operations by the means of core-size etc.
Does your project have a parallelization property like Janus, or do we have to implement it? If it is the latter case, what is your suggestion for us as a starting point?

**Comment by rayokota** [comment]
Hi @coxycoxwell , let me take a look at it and get back to you.

**Comment by coxycoxwell** [comment]
Thanks in advance! I am looking forward to hear from you!

**Comment by coxycoxwell** [comment]
Hi @rayokota , let me merge those changes in my copy and get back to you with the results.

**Comment by coxycoxwell** [comment]
Hi @rayokota , 
Those changes are OK for a query like g.V("X").outV() which would result in parallel. 
But I have a case that use a query like g.V("X").outV().outV(). The first depth results still come in parallel, but for each one of those first depth vertices, the system makes a "performEdgeScan" sequentially.
Is there a way to parallelize these scan operations?
Thank you!

**Comment by rayokota** [comment]
@coxycoxwell , ok, let me take a look again and get back to you.

**Comment by rayokota** [comment]
Hi @coxycoxwell , I wasn't able to spend much time on this.  If you're still interested in possibly implementing this yourself, you'll need to write a custom `ProviderOptimizationStrategy` as described here:  https://groups.google.com/d/msg/gremlin-users/QMVhLIPiGRE/gfdYOuCJEQAJ
