### ISSUE TITLE
Parallel loading performance still has some method to optimize

### ISSUE THREAD

**Issue by sleep-NULL** [rayokota/hgraphdb#61]
Now parallel loading only use parallel stream to accelerate query,  the Model only has load function to load single vertex or edge, HBase list get can reduce the overhead of rpc call, and a batch configuration can adjust the batch of list get

**Comment by rayokota** [comment]
Yes, I've been planning on switching to batch gets.   I'll work on a fix soon.

**Comment by sleep-NULL** [comment]
Thanks a lot, I'm looking forward your work
