### ISSUE TITLE
Best way to only add a vertex if not present?

### ISSUE THREAD

**Issue by tellisnz** [rayokota/hgraphdb#7]
Hi There,

If I'm using custom IDs for my vertices, what is the prescribed way to add a vertex with a particular ID that may already exist?

Doing something like this
```
Vertex vertex;
try {
  vertex = graph.vertex("my-id");
} catch (HBaseGraphNotFoundException e) {
  vertex = graph.addVertex(T.id, "my-id");
}
```
doesn't seem great, but the other methods like findVertex only seem to consult the cache instead of the DB?

Would using HBaseBulkLoader that doesn't check if it exists be a way around this? Is this a bit of a hack?

**Comment by rayokota** [comment]
Hi,

I would go with the following:

Vertex vertex;
try {
  vertex = graph.addVertex(T.id, "my-id");
} catch (IllegalArgumentException e) {
  // already exists
  vertex = graph.vertex("my-id");
}
